### ISSUE TITLE
Fix course layout style

### ISSUE THREAD

**Issue by arianerocha** [sumelms/frontend#121]
### Description

Fix CSS style to new the layout components

### Screenshots
![image](https://user-images.githubusercontent.com/3602349/200184150-a25bbd81-bd13-49ca-870f-518eec14dd05.png)

**Comment by mouracamila** [comment]
- [x] improve the header of page #128 
- [] improve breadcrumb
- []improve nav-items
- []improve the responsive layout
- []improve the container content
