### ISSUE TITLE
Verify the README information

### ISSUE THREAD

**Issue by rluders** [sumelms/frontend#28]
### Description

I was checking the README instructions, and it seems that some commands are not working. For example the one for `e2e` tests. In this case, I think that would be better to verify all the instructions, and also standardize the commands.

### Expected behavior

All the commands should be working.

### Additional context

We also need to give some option, like, you can run it with `yarn` or `npm`

**Comment by marianyfs** [comment]
I updated some README.md instructions when I added Cypress AXE and Storybook, tested all the commands and was able to run successfully (using yarn)

**Comment by rluders** [comment]
So, I guess that we are good. Thank you.
