### ISSUE TITLE
Testing are failing on CI

### ISSUE THREAD

**Issue by rluders** [sumelms/frontend#33]
### Description

I'm not sure if the issue was introduced by the #32 or if it was already there. Anyway, doesn't matter. We need to fix it.

### Steps to reproduce

1. Create a PR
2. [See the tests failing](https://travis-ci.com/github/sumelms/frontend/builds)

### Expected behavior

It should not fail.

### Screenshots

None.

### Desktop (please complete the following information):

None.

### Smartphone (please complete the following information):

None.

### Additional context

None.

**Comment by basask** [comment]
This issue first appears after PR #32

**Comment by basask** [comment]
It turns out it's an issue not related to the PR.

**Error message**: "Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it"

**Change**:
```diff
git diff HEAD^1
diff --git a/src/layouts/Default/Menu/index.tsx b/src/layouts/Default/Menu/index.tsx
index 1593d46..2659ee4 100644
--- a/src/layouts/Default/Menu/index.tsx
+++ b/src/layouts/Default/Menu/index.tsx
@@ -12,8 +12,8 @@ const Menu: React.FC = () => {
         <img src={logoImg} alt="Sumé" />
       </Brand>
 
-      <MenuButton icon={FiTrello} />
-      <MenuButton icon={FiFolder} />
+      <MenuButton icon={<FiTrello />} />
+      <MenuButton icon={<FiFolder />} />
     </Container>
   );
 };
```
