### ISSUE TITLE
Create Button Component

### ISSUE THREAD

**Issue by rluders** [sumelms/frontend#49]
### Description

Create a default Button component.

### UI Resource

![image](https://user-images.githubusercontent.com/191027/136689207-0ea350d7-54d2-492b-968d-0d64cd0ba51a.png)
![image](https://user-images.githubusercontent.com/191027/136689503-edfa7e71-b6b2-4a12-88f5-7317dad128f6.png)

> The image is just a guide/reference and some differences in the final result are acceptable upon review.

### API

n/a

### Additional Information

I think that it is possible to use the [react-avatar](https://github.com/Sitebase/react-avatar) or even take it as an example.

MUST:

- Accept prepend and append icons (#48)
- Accept different variants: default `bg-gray-100` , danger `bg-red-500`, info `bg-blue-500`, warning `bg-yellow-500`, success `bg-green-500`)
- Support outlined version
- Support the current states: `default/active`, `hover`, `focus`, `pressed` and `disabled`
- ATRIA attributes

DON'T:

- Write any custom CSS, please, use TailwindCSS only

### Possible unknowns

- Maybe the **DON'T** could be ignored if we find a way to use the [@apply utility](https://tailwindcss.com/docs/functions-and-directives#apply) to simplify the button variant styling.

### Dependencies

- [x] #48 

### Mentoring

**This task offers mentoring.**
If you need any help you can [join our Discord Server](https://discord.gg/NvjVTzPkCR) and talk with the following users:

- Ricardo Lüders (@rluders)
- Mariany (@marianyfs)

**Comment by mouracamila** [comment]
@marianyfs are you working on this one? If yes, could you assign yourself to it?
